### ISSUE TITLE
can't install on Ubuntu 10.04

### ISSUE THREAD

**Issue by zed** [bjpop/berp#2]
```
$ cabal install berp
Resolving dependencies...
cabal: cannot configure berp-0.0.1. It requires integer -any
There is no available version of integer that satisfies -any

$ cabal list integer
* AC-HalfInteger
    Synopsis: Efficient half-integer type.
    Latest version available: 1.2.1
    Latest version installed: [ Not installed ]
    License:  BSD3

* integer-gmp
    Synopsis: This package contains an Integer library based on GMP.
    Latest version available: [ Not available from server ]
    Latest version installed: 0.2.0.0
    License:  BSD3

$ cabal -V
cabal-install version 0.8.0
using version 1.8.0.2 of the Cabal library 

$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 6.12.1
```

Installation from source (after replacing `integer` with `integer-gmp`) also fails:

```
$ cabal install
Resolving dependencies...
cabal: dependencies conflict: ghc-6.12.1 requires containers ==0.3.0.0 however
containers-0.3.0.0 was excluded because berp-0.0.1 requires containers ==0.2.*

$ cabal info containers | grep 'version installed'
    Latest version installed: 0.3.0.0
```

**Comment by pheuter** [comment]
yep, same problems with me

**Comment by bjpop** [comment]
Some of the package dependencies in the cabal file were too tight. Also, there was an incorrect dependency on the integer package. I've loosened the constraints on dependencies somewhat and removed the dependency on integer.

This may fix the immediate problems you have, but note that there are other problems with building berp with ghc 6.12.x. Please see the notes about building berp on the githib wiki: http://wiki.github.com/bjpop/berp/installing-berp

**Comment by booherbg** [comment]
I am also having problems with dependencies on ubuntu 10.04. Specifically I can't build the process package which is the only package that depends on an older version of 'directory'.

here's my correspondence:

> hi there. i'd like to play around with berp to see how it works (i'm using python for my thesis). i've never used haskell or anything like it (i'm a python guy) so i'm new to this. i can't get all the dependencies to install for berp. i've used cabal and installed everything i can find that is depended upon, including alex and happy. berp-lib installs fine. but berp-compile throws an error that two different versions of directory are required by dependencies. ok whew.
> 
> So process is the only package that depends on an older version of directory. I found that with 'cpphs' i could reinstall it with cabal and that fixed the dependency problem because it rebuilt against the newest version of the dependency, but with process it won't build. For some reason process can't find runProcess.h even though it is on my system. It appears that the --extra-include-dirs= parameter, no matter where i put it with cabal, does not work as expected. Now I'm stuck.
> 
> any suggestions? I'm on ubuntu 10.04 x64...
> thanks,
> blaine
> 
> Here's my output:
> 
> [blaine@macbook:~/Dropbox/src/berp/compiler Tue Nov 08]
> 95$ cabal configure
> Resolving dependencies...
> Configuring berpcompiler-0.0.3...
> Warning: This package indirectly depends on multiple versions of the same
> package. This is highly likely to cause a compile failure.
> package process-1.0.1.2 requires directory-1.0.1.0
> package cpphs-1.13.2 requires directory-1.1.0.1
> package berplibs-0.0.3 requires directory-1.1.0.1
> package berpcompiler-0.0.3 requires directory-1.1.0.1
> 
> [blaine@macbook:~/Dropbox/src/berp/compiler Tue Nov 08]
> 92$ sudo cabal --extra-include-dirs=/usr/lib/ghc-6.12.1/process-1.0.1.2/include/ install process
> Resolving dependencies...
> Configuring process-1.1.0.0...
> configure: WARNING: unrecognized options: --with-compiler
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for pid_t... yes
> checking vfork.h usability... no
> checking vfork.h presence... no
> checking for vfork.h... no
> checking for fork... yes
> checking for vfork... yes
> checking for working fork... yes
> checking for working vfork... (cached) yes
> checking signal.h usability... yes
> checking signal.h presence... yes
> checking for signal.h... yes
> checking sys/wait.h usability... yes
> checking sys/wait.h presence... yes
> checking for sys/wait.h... yes
> checking fcntl.h usability... yes
> checking fcntl.h presence... yes
> checking for fcntl.h... yes
> checking for setitimer,... no
> checking for sysconf... yes
> checking value of SIG_DFL... -1
> checking value of SIG_IGN... -1
> configure: creating ./config.status
> config.status: creating include/HsProcessConfig.h
> config.status: include/HsProcessConfig.h is unchanged
> configure: WARNING: unrecognized options: --with-compiler
> cabal: Missing dependency on a foreign library:
> - Missing header file: runProcess.h
>   This problem can usually be solved by installing the system package that
>   provides this library (you may need the "-dev" version). If the library is
>   already installed but in a non-standard location then you can use the flags
>   --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
>   cabal: Error: some packages failed to install:
>   process-1.1.0.0 failed during the configure step. The exception was:
>   ExitFailure 1
> 
> [blaine@macbook:~/Dropbox/src/berp/compiler Tue Nov 08]
> 93$ ls /usr/lib/ghc-6.12.1/process-1.0.1.2/include/
> HsProcessConfig.h  runProcess.h
