### ISSUE TITLE
Still problem resolving dependencies

### ISSUE THREAD

**Issue by pheuter** [bjpop/berp#3]
➜  bjpop-berp-9a42791  cabal configure
Resolving dependencies...
Configuring berp-0.0.2...
cabal: At least the following dependencies are missing:
ghc-paths ==0.1._,
haskeline ==0.6._,
haskell-src-exts ==1.9._,
language-python ==0.3._,
monads-tf ==0.1._,
parseargs ==0.1._,
transformers ==0.2.*

**Comment by bjpop** [comment]
Do you have those packages installed?
If not, then you need to install them.

If yes, then please report:
- the version of ghc you are using
- the operating system you are using (and version)
- the version of cabal you are using
- how you obtained the source code of berp

**Comment by pheuter** [comment]
yeah, language-python fails on ghc 6.12

**Comment by bjpop** [comment]
This is caused by a bug in GHC. See the comments in http://wiki.github.com/bjpop/berp/installing-berp
