### ISSUE TITLE
Error evaluating in the interpreter

### ISSUE THREAD

**Issue by ajhager** [bjpop/berp#4]
`>>> 1`

berp: /home/aajhager/.cabal/lib/berp-0.0.3/ghc-6.12.1/HSberp-0.0.3.o: unknown symbol 'berpzm0zi0zi3_Pathszuberp_version1_closure'
berp: unable to load package 'berp-0.0.3'
Not in scope: 'init'

Using 6.12.1

Compilation works great but trying to evaluate anything in the interpreter causes that error to spit out.

**Comment by ajhager** [comment]
The latest trunk fixes it. Thanks.

**Comment by bjpop** [comment]
That was quick!

Sorry about the error. I made a previous change which grabbed the version number of berp from the cabal generated module called Paths_berp. However, I forgot to add that module to the .cabal file. This caused the interpreter to fail on linking.

I have now added Paths_berp to the .cabal file to fix the problem.

Thanks for the report.
