### ISSUE TITLE
Build failure on GHC 7.0.1

### ISSUE THREAD

**Issue by xrl** [bjpop/berp#5]
I was looking at the berp hackage page, http://hackage.haskell.org/package/berp , and I came across an error indicating incompability with GHC 7.0.1:

http://hackage.haskell.org/packages/archive/berp/0.0.2/logs/failure/ghc-7.0

**Comment by bjpop** [comment]
Thanks xrl.

From the build error we see a problem with the constrain on the version number of containers. Berp is set to < 0.4, whereas GHC 7.0.1 appears to require == 0.4.

I haven't had time to try to build it with GHC 7.x (which I admit has been out for quite a while now). I'm currently in the midst of a major update, so I probably won't fix the build issue until then.

Perhaps you can download the code and see if it builds with a modified constraint on the containers library?

**Comment by cartazio** [comment]
has anyone else had a go at this problem now that 7.2.\* is out?
