### ISSUE TITLE
berp support for python's math library

### ISSUE THREAD

**Issue by booherbg** [bjpop/berp#6]
Is it possible to get berp to use haskell's math routines in place of python's math library? That'd be great!

The other solution would be to find a pure python implementation of python's math library. I don't know how to do log, log10, pow, exp, etc. in pure python but I'm sure it isn't hard. Does anyone want to take a whack at it?

Blaine

**Comment by bjpop** [comment]
Hi Blaine,

It is in theory not a difficult thing to do. However, berp is not
really ready for serious user development yet. So fleshing out the
standard libraries is not one of my main goals at the moment.

One thing it really needs is better support for modules. I've got a
branch under development which has this, but it won't be ready for a
while.

If you feel brave, you could have a go at adding features yourself,
but it depends on how keen you are and how much experience you've had
with Haskell.

Cheers,
Bernie.

On 16 November 2011 10:20, Blaine
reply@reply.github.com
wrote:

**Comment by booherbg** [comment]
Thanks Bernie, that makes sense. I need to get some more haskell under my
belt before I take that on. Sounds like a fun project, though. Thanks!
Blaine

On Sun, Nov 20, 2011 at 4:06 AM, Bernie Pope <
reply@reply.github.com
